#### 1. Import libraries

In [29]:
import torch, torchvision
import numpy as np
import math
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn import datasets

#### 2. Create the dataset class

In [4]:
class winedata(Dataset):
    def __init__(self):
        # load dataset
        self.data = datasets.load_wine()
        self.X =  torch.from_numpy((self.data.data).astype(np.float32))
        self.y =  torch.from_numpy((self.data.target).astype(np.float32))
        self.n_samples = self.X.shape[0]
                
    def __getitem__(self, index):
        # get the row of the dataset accoding to the index
        # dataset[0]
        return self.X[index], self.y[index]        
    
    def __len__(self):
        # return the len of dataset
        return self.n_samples
    
# create instance of the dataset
dataset = winedata()

In [5]:
# check ith item and the len
print(dataset.__len__())
print(dataset.__getitem__(1))

178
(tensor([1.3200e+01, 1.7800e+00, 2.1400e+00, 1.1200e+01, 1.0000e+02, 2.6500e+00,
        2.7600e+00, 2.6000e-01, 1.2800e+00, 4.3800e+00, 1.0500e+00, 3.4000e+00,
        1.0500e+03]), tensor(0.))


#### 3. Dataloader

##### 3.1 How a batch is created

In [6]:
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True, num_workers = 0)
# dataloader is now an iterable object

dataiter = iter(dataloader)
feature, label = next(dataiter)
print(feature)
print(label)

tensor([[1.2720e+01, 1.7500e+00, 2.2800e+00, 2.2500e+01, 8.4000e+01, 1.3800e+00,
         1.7600e+00, 4.8000e-01, 1.6300e+00, 3.3000e+00, 8.8000e-01, 2.4200e+00,
         4.8800e+02],
        [1.3300e+01, 1.7200e+00, 2.1400e+00, 1.7000e+01, 9.4000e+01, 2.4000e+00,
         2.1900e+00, 2.7000e-01, 1.3500e+00, 3.9500e+00, 1.0200e+00, 2.7700e+00,
         1.2850e+03],
        [1.3050e+01, 1.6500e+00, 2.5500e+00, 1.8000e+01, 9.8000e+01, 2.4500e+00,
         2.4300e+00, 2.9000e-01, 1.4400e+00, 4.2500e+00, 1.1200e+00, 2.5100e+00,
         1.1050e+03],
        [1.2070e+01, 2.1600e+00, 2.1700e+00, 2.1000e+01, 8.5000e+01, 2.6000e+00,
         2.6500e+00, 3.7000e-01, 1.3500e+00, 2.7600e+00, 8.6000e-01, 3.2800e+00,
         3.7800e+02]])
tensor([1., 0., 0., 1.])


##### 3.2 Dummy training loop

In [61]:
# hyperparameters
epochs = 2
batch_size = 4
num_workers = 0
total_samples = len(dataset)
n_iter = math.ceil(total_samples/batch_size)

print(total_samples, n_iter)

178 45


In [64]:
# training loop

for epoch in range(epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        
        # forward pass , loss , backward pass goes here
        
        if (i+1) % 5 == 0:
            print(f'epoch : {epoch+1}/{epochs}, steps : {i+1}/{n_iter}, inputs : {inputs.shape}')
        

epoch : 1/2, steps : 5/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 10/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 15/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 20/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 25/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 30/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 35/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 40/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 45/45, inputs : torch.Size([2, 13])
epoch : 2/2, steps : 5/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 10/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 15/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 20/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 25/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 30/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 35/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 40/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 45/45, input

#### 4. DataTransforms

In [7]:
class winedata(Dataset):
    def __init__(self, transform = None):
        # load dataset
        self.data = datasets.load_wine()
        self.X = self.data.data
        self.y = self.data.target
        self.n_samples = self.X.shape[0]
        self.transform = transform
        
        print(f'type of X : {type(self.X)}')
        print(f'type of y : {type(self.y)}')
                
    def __getitem__(self, index):
        # get the row of the dataset accoding to the index
        # dataset[0]
        sample =  np.array(self.X[index]), np.array(self.y[index]) 
              

        #check if transform exists, and apply the transformation
        if self.transform:
            sample = self.transform(sample)
            
        return sample
        
    def __len__(self):
        # return the len of dataset
        return self.n_samples
    
dataset = winedata()
dataset.__getitem__(0)

# out output is an array over here as we havent specified any transformations

type of X : <class 'numpy.ndarray'>
type of y : <class 'numpy.ndarray'>


(array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03]),
 array(0))

##### Create custom class for transforming the samples to tensors

In [122]:
class To_Tensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

#### Check before/after applying the transform

In [125]:
# before using transform we get the result as a np array

dataset = winedata()
print((dataset.__getitem__(0)[0]))
print(type(dataset.__getitem__(0)[0]))

type of X : <class 'numpy.ndarray'>
type of y : <class 'numpy.ndarray'>
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
<class 'numpy.ndarray'>


In [131]:
# after applying the transform, we get the np array converted to tensor

dataset2 = winedata(transform=To_Tensor())
print(dataset2.__getitem__(0))
print(f' \nConverted Datatype : {type(dataset2.__getitem__(0)[0])}')

type of X : <class 'numpy.ndarray'>
type of y : <class 'numpy.ndarray'>
(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03], dtype=torch.float64), tensor(0, dtype=torch.int32))
 
Converted Datatype : <class 'torch.Tensor'>


##### Apply multiple transformations

In [32]:
# you can also apply different kinds of transformations

class MulTransform:
    def __init__(self, factor):
        self.factor = factor
        
    def __call__(self, sample):
        inputs, target = sample
        inputs *= self.factor
        # multiply the feature by the factor    
        return inputs, target

class To_Tensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)
    

# Define dataset class
class winedata(Dataset):
    def __init__(self, transform = None):
        # load dataset
        self.data = datasets.load_wine()
        self.X = self.data.data
        self.y = self.data.target
        self.n_samples = self.X.shape[0]
        self.transform = transform
        
        print(f'type of X : {type(self.X)}')
        print(f'type of y : {type(self.y)}')
                
    def __getitem__(self, index):
        # get the row of the dataset accoding to the index
        # dataset[0]
        sample =  np.array(self.X[index]), np.array(self.y[index]) 
              

        #check if transform exists, and apply the transformation
        if self.transform:
            sample = self.transform(sample)
            
        return sample
        
    def __len__(self):
        # return the len of dataset
        return self.n_samples
    


##### Create transform.compose method

In [34]:
composed = torchvision.transforms.Compose([To_Tensor(), MulTransform(2)])

##### Apply the transform.compose on the class dataset

In [35]:
## before
print(f"{'*' * 40} BRFORE {'*' * 40}\n")
dataset = winedata()
print(dataset.__getitem__(0))
type(dataset.__getitem__(0)[0])

## after
print(f"{'*' * 40} AFTER {'*' * 40}\n")
dataset = winedata(transform=composed)
print(dataset.__getitem__(0))
type(dataset.__getitem__(0)[0])

**************************************** BRFORE ****************************************

type of X : <class 'numpy.ndarray'>
type of y : <class 'numpy.ndarray'>
(array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03]), array(0))
**************************************** AFTER ****************************************

type of X : <class 'numpy.ndarray'>
type of y : <class 'numpy.ndarray'>
(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03], dtype=torch.float64), tensor(0, dtype=torch.int32))


torch.Tensor

##### We can observe that the output is a tensor and it is multiplied by factor (2) passed in the mulTransform