#### 1. Import libraries

In [57]:
import torch
import numpy as np
import math
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn import datasets

#### 2. Create the dataset class

In [37]:
class winedata(Dataset):
    def __init__(self):
        # load dataset
        self.data = datasets.load_wine()
        self.X =  torch.from_numpy((self.data.data).astype(np.float32))
        self.y =  torch.from_numpy((self.data.target).astype(np.float32))
        self.n_samples = self.X.shape[0]
                
    def __getitem__(self, index):
        # get the row of the dataset accoding to the index
        # dataset[0]
        return self.X[index], self.y[index]        
    
    def __len__(self):
        # return the len of dataset
        return self.n_samples
    
# create instance of the dataset
dataset = winedata()

In [38]:
# check ith item and the len
print(dataset.__len__())
print(dataset.__getitem__(1))

178
(tensor([1.3200e+01, 1.7800e+00, 2.1400e+00, 1.1200e+01, 1.0000e+02, 2.6500e+00,
        2.7600e+00, 2.6000e-01, 1.2800e+00, 4.3800e+00, 1.0500e+00, 3.4000e+00,
        1.0500e+03]), tensor(0.))


#### 3. Dataloader

##### 3.1 How a batch is created

In [56]:
dataloader = DataLoader(dataset = dataset, batch_size = 4, shuffle = True, num_workers = 0)
# dataloader is now an iterable object

dataiter = iter(dataloader)
feature, label = next(dataiter)
print(feature)
print(label)

tensor([[1.1650e+01, 1.6700e+00, 2.6200e+00, 2.6000e+01, 8.8000e+01, 1.9200e+00,
         1.6100e+00, 4.0000e-01, 1.3400e+00, 2.6000e+00, 1.3600e+00, 3.2100e+00,
         5.6200e+02],
        [1.1840e+01, 2.8900e+00, 2.2300e+00, 1.8000e+01, 1.1200e+02, 1.7200e+00,
         1.3200e+00, 4.3000e-01, 9.5000e-01, 2.6500e+00, 9.6000e-01, 2.5200e+00,
         5.0000e+02],
        [1.4060e+01, 1.6300e+00, 2.2800e+00, 1.6000e+01, 1.2600e+02, 3.0000e+00,
         3.1700e+00, 2.4000e-01, 2.1000e+00, 5.6500e+00, 1.0900e+00, 3.7100e+00,
         7.8000e+02],
        [1.1450e+01, 2.4000e+00, 2.4200e+00, 2.0000e+01, 9.6000e+01, 2.9000e+00,
         2.7900e+00, 3.2000e-01, 1.8300e+00, 3.2500e+00, 8.0000e-01, 3.3900e+00,
         6.2500e+02]])
tensor([1., 1., 0., 1.])


##### 3.2 Dummy training loop

In [61]:
# hyperparameters
epochs = 2
batch_size = 4
num_workers = 0
total_samples = len(dataset)
n_iter = math.ceil(total_samples/batch_size)

print(total_samples, n_iter)

178 45


In [64]:
# training loop

for epoch in range(epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        
        # forward pass , loss , backward pass goes here
        
        if (i+1) % 5 == 0:
            print(f'epoch : {epoch+1}/{epochs}, steps : {i+1}/{n_iter}, inputs : {inputs.shape}')
        

epoch : 1/2, steps : 5/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 10/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 15/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 20/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 25/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 30/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 35/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 40/45, inputs : torch.Size([4, 13])
epoch : 1/2, steps : 45/45, inputs : torch.Size([2, 13])
epoch : 2/2, steps : 5/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 10/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 15/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 20/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 25/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 30/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 35/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 40/45, inputs : torch.Size([4, 13])
epoch : 2/2, steps : 45/45, input